### ISSUE TITLE
Nueva entidad Detalle Receta

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_lh_p3_g2_sf#12]
Crear una nueva entidad `DetalleReceta` en el paquete `entity` con los siguientes atributos:

* id
* receta (String)
* medicamento (String)

**Requisitos:**

* Eliminar constructores no utilizados y anotaciones redundantes.
* Incluir una captura de pantalla de la tabla `DetalleReceta` generada en la base de datos en el pull request.

**Comment by christianT30** [comment]
![60db5973-a362-49a4-863f-174e2a49a8a6](https://github.com/ahumadamob/2024_lh_p3_g2_sf/assets/167476900/3fc30c1b-c7dd-480e-8942-e5be99ac893d)
