### ISSUE TITLE
Persistencia simple entidad Obra Social

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_lh_p3_g2_sf#32]

**Comment by ahumadamob** [comment]
Ejercicio sin resolver en la revisión 17/9

**Comment by christianT30** [comment]
los cambios para esta issue los agregue a 43-fix-master
![image](https://github.com/user-attachments/assets/7cfdca98-487e-4510-89d7-3863aa5a3061)

**Comment by christianT30** [comment]
![image](https://github.com/user-attachments/assets/605fabfe-b28c-4801-9ddb-0793730f443c)
![image](https://github.com/user-attachments/assets/8c025e3a-ddb9-4cbf-acc0-66dc103476a6)
![image](https://github.com/user-attachments/assets/224da87b-12a2-411d-98de-325b81d2cb88)
![image](https://github.com/user-attachments/assets/5a0640fd-8ee1-47f4-97da-69e9c2457d8b)
