### ISSUE TITLE
Refactorización de EspecialidadController

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_lh_p3_g2_sf#50]
**Issue: Refactorización de EspecialidadController para uso de DTO, manejo de códigos de respuesta y mejoras generales**

**Descripción:**
El objetivo es mejorar el controlador de la entidad `Especialidad`, incorporando un manejo más robusto y consistente de las respuestas y los códigos HTTP, utilizando un DTO genérico para estandarizar las respuestas y añadir validaciones y manejo de excepciones.

**Tareas:**

1. **Uso del DTO genérico:**
   - Refactorizar los métodos del controlador (`mostrarTodasLasEspecialidades`, `mostrarEspecialidadPorId`, `crearRegistro`, `actualizarRegistro`, `eliminarRegistro`) para que todos devuelvan un DTO estandarizado que encapsule los datos de `Especialidad`, el estado de la operación y los mensajes de error.

2. **Manejo de códigos de respuesta HTTP:**
   - Al crear una especialidad correctamente, devolver `201 Created`.
   - Al actualizar una especialidad existente, devolver `200 OK`.
   - Si se intenta acceder o eliminar una especialidad que no existe, devolver `404 Not Found`.
   - Si hay errores de validación en los datos enviados, devolver `400 Bad Request`.
   - Para otros errores inesperados, devolver `500 Internal Server Error`.

3. **Validaciones y manejo de errores:**
   - Implementar validaciones para los campos de la entidad `Especialidad` usando anotaciones como `@Valid` y manejar los errores devolviendo `400 Bad Request`.
   - Asegurarse de que el controlador valide correctamente la existencia de una especialidad antes de intentar actualizarla o eliminarla.

4. **Manejador global de excepciones:**
   - Crear un manejador global de excepciones utilizando `@ControllerAdvice` para gestionar las excepciones comunes, como `EntityNotFoundException` y `ValidationException`, de manera centralizada.

**Criterios de aceptación:**
- Todos los endpoints del controlador deben devolver respuestas encapsuladas en un DTO.
- Los códigos de respuesta HTTP deben reflejar el resultado de la operación correctamente.
- El controlador debe incluir validaciones adecuadas y manejo de errores en todas las operaciones.
- El manejador global de excepciones debe estar implementado y funcionando correctamente.

**Capturas de pantalla:**
- Adjuntar capturas de pantalla de Postman con los siguientes casos de prueba:
   - `201 Created` al crear una nueva especialidad.
   - `404 Not Found` al intentar acceder o eliminar una especialidad inexistente.
   - `400 Bad Request` al enviar datos inválidos al crear o actualizar una especialidad.
   - `200 OK` al actualizar un registro de especialidad existente.

**Comment by ValentiGil** [comment]
**Endpoints Get**
![image](https://github.com/user-attachments/assets/4eba36cf-b8b7-4d03-a72d-2b84826b2620)
![image](https://github.com/user-attachments/assets/aafdd21c-e004-49ca-a671-d0225a70f313)
![image](https://github.com/user-attachments/assets/25b52f45-78d1-47c8-aa21-f1be12d9f2fc)

**Endpoints Post**
![image](https://github.com/user-attachments/assets/0e8c42c0-9352-4e28-9c31-cfb777107cb4)
![image](https://github.com/user-attachments/assets/107de32c-8a16-453b-8609-721d0e077582)


**Endpoints Put**
![image](https://github.com/user-attachments/assets/85490896-8edc-43bb-9c60-2c0c4194b0ba)

**Endpoints Delete**
![image](https://github.com/user-attachments/assets/76acf26c-90fc-495b-a1b1-f059c092dbdd)
![image](https://github.com/user-attachments/assets/638fd2fa-b7b4-4e82-ac81-f00af9f64cb1)

**Comment by ahumadamob** [comment]
Aceptada, pero hacer el merge al master al final

**Comment by ahumadamob** [comment]
Te he asignado una nueva branch para que trabajes en esta issue: 50-refactorización-de-especialidadcontroller-fix. Debes cambiarte a esta rama y reconfigurar la aplicación como lo vimos en clase.

**Comment by ahumadamob** [comment]
Tu trabajo no cumple con el punto 4. Manejador global de excepciones
