### ISSUE TITLE
Refactorización de ObraSocialController

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_lh_p3_g2_sf#72]
**Issue: Refactorización de ObraSocialController para uso de DTO, manejo de códigos de respuesta y mejoras generales**

**Descripción:**
El objetivo es mejorar el controlador de la entidad `ObraSocial`, incorporando un manejo más robusto y consistente de las respuestas y los códigos HTTP. Se debe utilizar un DTO genérico para estandarizar las respuestas y añadir validaciones y manejo de excepciones.

**Tareas:**

1. **Uso del DTO genérico:**
   - Refactorizar los métodos del controlador (`mostrarTodasLasObrasSociales`, `mostrarObraSocialPorId`, `crearObraSocial`, `actualizarObraSocial`, `eliminarObraSocial`) para que todos devuelvan un DTO estandarizado que encapsule los datos de `ObraSocial`, el estado de la operación y los mensajes de error.

2. **Manejo de códigos de respuesta HTTP:**
   - Al crear una obra social correctamente, devolver `201 Created`.
   - Al actualizar una obra social existente, devolver `200 OK`.
   - Si se intenta acceder o eliminar una obra social que no existe, devolver `404 Not Found`.
   - Si hay errores de validación en los datos enviados, devolver `400 Bad Request`.
   - Para otros errores inesperados, devolver `500 Internal Server Error`.

3. **Validaciones y manejo de errores:**
   - Implementar validaciones para los campos de la entidad `ObraSocial` usando anotaciones como `@Valid` y manejar los errores devolviendo `400 Bad Request`.
   - Asegurarse de que el controlador valide correctamente la existencia de una obra social antes de intentar actualizarla o eliminarla.

4. **Manejador global de excepciones:**
   - Crear un manejador global de excepciones utilizando `@ControllerAdvice` para gestionar las excepciones comunes, como `EntityNotFoundException` y `ValidationException`, de manera centralizada.

**Criterios de aceptación:**
- Todos los endpoints del controlador deben devolver respuestas encapsuladas en un DTO.
- Los códigos de respuesta HTTP deben reflejar el resultado de la operación correctamente.
- El controlador debe incluir validaciones adecuadas y manejo de errores en todas las operaciones.
- El manejador global de excepciones debe estar implementado y funcionando correctamente.

**Capturas de pantalla:**
- Adjuntar capturas de pantalla de Postman con los siguientes casos de prueba:
   - `201 Created` al crear una nueva obra social.
   - `404 Not Found` al intentar acceder o eliminar una obra social inexistente.
   - `400 Bad Request` al enviar datos inválidos al crear o actualizar una obra social.
   - `200 OK` al actualizar un registro de obra social existente.

**Comment by christianT30** [comment]
![f34bc42a-88b4-4d18-bfaf-2344f1cd31e0](https://github.com/user-attachments/assets/a5fabecd-d1b5-49c5-8477-1f74c976e37d)
![9ac9ca5a-5d10-47e6-8d87-feea8ada2929](https://github.com/user-attachments/assets/cf3497b0-8c6d-4370-980a-1936a29e5de0)
![c8bd5f23-f054-450e-b688-2b046d3b6db5](https://github.com/user-attachments/assets/8242a154-5464-48a4-a212-870ce7a93310)
![c8d1b398-eb33-4658-b01f-d25c8ad32eb9](https://github.com/user-attachments/assets/02c6bce0-41a4-4161-b5ad-ce5cc8f2bbdf)
![4782df30-9299-4679-936b-378b66e4bf09](https://github.com/user-attachments/assets/7bbf0306-0c0b-4c46-bd54-ca23dcd8b5ec)


![d136c736-7886-4a7c-accd-ec3d23d947cb](https://github.com/user-attachments/assets/910635c3-6d1f-4739-ba04-d8ce3c6cf884)
![045c223f-c7a7-471e-ae59-69c87bd8cf68](https://github.com/user-attachments/assets/108847ba-398d-4b78-9c2a-696258683f88)
